Invoke a sub-command, expose argument parser.
Closes #11.

diff --git a/homeport b/homeport
--- a/homeport
+++ b/homeport
@@ -1,17 +1,60 @@
 #!/bin/bash
 
+set -e
+
+
+case "$OSTYPE" in
+    darwin* )
+        HOMEPORT_OS=OSX
+        ;;
+    linux* )
+        HOMEPORT_OS=Linux
+        ;;
+    * )
+        abend "Homeport will only run on OS X or Linux."
+        ;;
+esac
+
 if [ "$1" == "module" ]; then
+    echo $0
   echo "Please do not execute these programs directly. Use homeport."
   exit 1
 fi
 
-echo "$(dirname $0)"
+# At the top of every module. This will gather a usage message to share with the
+# user if we abend.
+function homeport() {
+    [ "$1" == "module" ] || fail "invalid argument to homeport"
+    local message; local spaces;
+    IFS="\000" read -r -d'\000' message && true
+    spaces=$(
+        echo "$message" | sed -e '/^$/d' -e 's/^\( *\).*/\1/' | \
+            sed -e '1h;H;g;s/[^\n]/#/g;s/\(#*\)\n\1/\n/;G;/^\n/s/\n.*\n\(.*\)\n.*/\1/;s/.*\n//;h;$!d'
+    )
+    USAGE="$(echo "$message" | sed -e "s/^$spaces//")"
+}
 
-pushd $(dirname $0) > /dev/null
-HOMEPORT_PATH=$(pwd -P)
-popd > /dev/null
+function homeport_readlink() {
+    file=$1
+    if [ "$HOMEPORT_OS" = "OSX" ]; then
+        if [ -L "$file" ]; then
+            readlink $1
+        else
+            echo "$file"
+        fi
+    else
+        readlink -f $1
+    fi
+}
 
-source "$HOMEPORT_PATH/getopt.bash"
+function homeport_absolutize() {
+    expanded=$(cd ${1/*} && homeport_readlink $1)
+    readlink $1 1>&2
+    echo x $expanded 1>&2
+    base=${expanded##*/}
+    dir=$(cd ${expanded%/*} && pwd -P)
+    echo "$dir/$base"
+}
 
 function usage() {
   local code=$1
@@ -37,9 +80,23 @@ function homeport_exec() {
     shift
 
     export HOMEPORT_PATH
-    export -f usage abend getopt
+    export -f usage abend getopt homeport
 
     "$action" $@
 }
+
+homeport_file=$0
+
+while [ -L "$homeport_file" ]; do
+    expanded=$(homeport_readlink "$homeport_file")
+    pushd "${homeport_file%/*}" > /dev/null
+    pushd "${expanded%/*}" > /dev/null
+    HOMEPORT_PATH=$(pwd)
+    popd > /dev/null
+    popd > /dev/null
+    homeport_file="$HOMEPORT_PATH/${homeport_file##*/}"
+done
+
+source "$HOMEPORT_PATH/getopt.bash"
 
 homeport_exec $@
